=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/resources/documentation.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.xml-sicherheit.de" targetNamespace="http://www.xml-sicherheit.de" xml:lang="en">	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>	<xs:annotation>		<xs:documentation xml:lang="en">			XML-Security Plug-in documentation schema. Used for online help and tutorials.		</xs:documentation>	</xs:annotation>	<xs:element name="title" type="xs:string"/>	<xs:element name="strong" type="xs:string"/>	<xs:element name="keyword" type="xs:string"/>	<xs:element name="definition" type="xs:string"/>	<xs:element name="description" type="xs:string"/>	<xs:element name="headline">		<xs:complexType>			<xs:simpleContent>				<xs:extension base="xs:string">					<xs:attribute name="id" type="xs:ID" use="required"/>				</xs:extension>			</xs:simpleContent>		</xs:complexType>	</xs:element>	<xs:element name="data">		<xs:complexType mixed="true">			<xs:sequence>				<xs:element ref="strong" minOccurs="0" maxOccurs="unbounded"/>				<xs:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="acronyms">		<xs:complexType>			<xs:sequence>				<xs:element ref="acronym" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="acronym">		<xs:complexType>			<xs:sequence>				<xs:element ref="definition"/>				<xs:element ref="description"/>			</xs:sequence>			<xs:attribute name="abbreviation" type="xs:ID" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="chapter">		<xs:complexType>			<xs:sequence>				<xs:element ref="title" minOccurs="0"/>				<xs:element ref="text"/>			</xs:sequence>			<xs:attribute name="category" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="general"/>						<xs:enumeration value="basics"/>						<xs:enumeration value="plugin"/>						<xs:enumeration value="resources"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute ref="xml:lang" use="required"/>			<xs:attribute ref="xml:id" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="text">		<xs:complexType>			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="p"/>				<xs:element ref="list"/>				<xs:element ref="code"/>				<xs:element ref="table"/>				<xs:element ref="headline"/>				<xs:element ref="link"/>				<xs:element ref="image"/>				<xs:element ref="resources" minOccurs="0"/>				<xs:element ref="acronyms" minOccurs="0"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="p">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="strong"/>				<xs:element ref="keyword"/>				<xs:element ref="link"/>				<xs:element ref="eclipse"/>			</xs:choice>			<xs:attribute name="id" type="xs:ID" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="list">		<xs:complexType>			<xs:choice maxOccurs="unbounded">				<xs:element ref="point"/>				<xs:element ref="list"/>			</xs:choice>			<xs:attribute name="type" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="ordered"/>						<xs:enumeration value="unordered"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="point">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="strong"/>				<xs:element ref="keyword"/>				<xs:element ref="link"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="link">		<xs:complexType mixed="true">			<xs:sequence>				<xs:element ref="image" minOccurs="0"/>			</xs:sequence>			<xs:attribute name="id" type="xs:anyURI" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="image">		<xs:complexType>			<xs:attribute name="id" type="xs:anyURI" use="required"/>			<xs:attribute name="title" type="xs:string" use="required"/>			<xs:attribute name="width" use="required">				<xs:simpleType>					<xs:restriction base="xs:positiveInteger">						<xs:minInclusive value="1"/>						<xs:maxInclusive value="800"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute name="height" use="required">				<xs:simpleType>					<xs:restriction base="xs:positiveInteger">						<xs:minInclusive value="1"/>						<xs:maxInclusive value="800"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="table">		<xs:complexType>			<xs:sequence>				<xs:element ref="head"/>				<xs:element ref="row" maxOccurs="unbounded"/>			</xs:sequence>			<xs:attribute name="width" type="xs:positiveInteger" use="optional"/>			<xs:attribute name="border" type="xs:positiveInteger" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="head">		<xs:complexType>			<xs:sequence>				<xs:element ref="data" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="row">		<xs:complexType>			<xs:sequence>				<xs:element ref="data" maxOccurs="unbounded"/>			</xs:sequence>			<xs:attribute name="valign" type="xs:string" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="resources">		<xs:complexType>			<xs:sequence>				<xs:element ref="title"/>				<xs:element ref="link" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="code">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="link"/>			</xs:choice>		</xs:complexType>	</xs:element></xs:schema>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/signatures_syntax_signedinfo.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="signatures_syntax_signedinfo" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Das SignedInfo Element</title>	<text>		<p>Das erste und auch komplexeste Element innerhalb von <link id="signatures_syntax_signature.html">Signature</link> ist <strong>SignedInfo</strong> und enthält die verwendeten Algorithmen zur Kanonisierung und Signierung, eine oder mehrere Referenzen auf die signierten Daten, eventuelle Transformationen und die Hashwerte dieser Daten. <strong>SignedInfo</strong> enthält also alle Informationen zu den zu signierenden Ressourcen und ist damit der Teil, über den die digitale Signatur erstellt wird.</p>		<p>Mit dem Signieren der verwendeten Algorithmen erhöht sich die Sicherheit. Ein sicherer Algorithmus kann so nicht gegen einen unsicheren ausgetauscht werden, ohne dass die Signatur ungültig wird.</p>		<p>Weitere Eigenschaften, wie z.B. ein Zeitstempel oder die Seriennummer der verwendeten kryptografischen Hardware, können nur durch ein oder mehrere optionale Kindelemente <link id="signatures_syntax_object.html#SignatureProperties">SignatureProperties</link> in einem <link id="signatures_syntax_object.html">Object</link> Element angegeben werden. Für einen Zeitstempel existiert dazu beispielsweise das Element <keyword>timestamp</keyword>, mit dem ein Zeitstempel vor der Erstellung der Signatur in die signierten Daten eingebunden werden kann.</p>		<p>			<strong>SignedInfo</strong> kann ein optionales Attribut <keyword>Id</keyword> enthalten mit dem das Element z.B. von anderen Signaturen referenziert werden kann. Kindelemente von <strong>SignedInfo</strong> sind die Pflichtelemente <link id="signatures_syntax_signedinfo.html#CanonicalizationMethod">CanonicalizationMethod</link> und <link id="signatures_syntax_signedinfo.html#SignatureMethod">SignatureMethod</link> sowie ein oder mehrere <link id="signatures_syntax_signedinfo.html#Reference">Reference</link> Elemente.</p>		<headline id="CanonicalizationMethod">CanonicalizationMethod</headline>		<p>Das leere Pflichtelement <strong>CanonicalizationMethod</strong> enthält ein <keyword>Algorithm</keyword> Attribut zur Identifikation des <link id="signatures_canon.html">Kanonisierungs-Algorithmus</link>, der vor der Signaturberechnung auf die Daten in <link id="signatures_syntax_signedinfo.html">SignedInfo</link> angewendet wird. Die möglichen Werte des URI finden sich in der Tabelle bei der <link id="signatures_canon.html">Kanonisierung</link>.</p>		<headline id="SignatureMethod">SignatureMethod</headline>		<p>			<strong>SignatureMethod</strong> ist ebenfalls ein leeres Pflichtelement mit einem <keyword>Algorithm</keyword> Attribut und gibt den zur Signaturgenerierung (und später zur Verifizierung) verwendeten Algorithmus an. Mit diesem Algorithmus wird das kanonische <link id="signatures_syntax_signedinfo.html">SignedInfo</link> Element in den <link id="signatures_syntax_signaturevalue.html">SignatureValue</link> konvertiert. Der URI kann die in der folgenden Tabelle aufgeführten Werte annehmen. Die Verwendung von weiteren Algorithmen ist möglich, aber von der konkreten Implementierung abhängig.</p>		<table>			<head>				<data>Name</data>				<data>URI</data>				<data>Implementierung</data>			</head>			<row>				<data>					<strong>DSA with SHA 1 (DSS)</strong>				</data>				<data>http://www.w3.org/2000/09/xmldsig#dsa-sha1</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>HMAC-SHA 1</strong>				</data>				<data>http://www.w3.org/2000/09/xmldsig#hmac-sha1</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>RSA with SHA 1</strong>				</data>				<data>http://www.w3.org/2000/09/xmldsig#rsa-sha1</data>				<data>empfohlen</data>			</row>		</table>		<headline id="Reference">Reference</headline>		<p>Es folgen mindestens ein oder mehrere <strong>Reference</strong> Elemente, die angeben, welche beliebigen, auch binären, Daten in die Signaturberechnung miteinbezogen werden sollen. Die <strong>Reference</strong> Elemente stellen somit den Kern einer Signatur dar. Mehrere <strong>Reference</strong> Elemente entsprechen einer Sammelsignatur, also dem Signieren von mehreren Objekten mit einer Signatur. Jedes Element steht dabei für einen signierten Inhalt.</p>		<p>XML-Signaturen signieren niemals direkt die Ressourcen, sondern legen zunächst eine Liste von Hashwerten dieser an. Diese Liste wird dann mit einem Signatur-Algorithmus signiert. Damit wird nicht nur die Signatur-Operation beschleunigt, sondern auch ein einfacher Weg angeboten, um mehrere Ressourcen gleichzeitig zu signieren.</p>		<p>Zum <strong>Reference</strong> Element gehören drei optionale Attribute: <keyword>Id</keyword>, <keyword>Type</keyword> und <keyword>URI</keyword>. <keyword>Id</keyword> vom Typ ID dient der Identifizierung der Referenz. Das Attribut <keyword>Type</keyword> vom Typ anyURI bestimmt mit dem als Attributwert angegebenen URI den Typ der Referenz. Das Attribut bezieht sich nicht auf die referenzierten Daten, sondern auf den Container, der die Daten enthält. Damit kann angezeigt werden ob es sich bei der Referenz um ein <link id="signatures_syntax_object.html">Object</link>, <link id="signatures_syntax_object.html#SignatureProperties">SignatureProperty</link> oder <link id="signatures_syntax_object.html#Manifest">Manifest</link> Element handelt.</p>		<p>Das dritte Attribut <keyword>URI</keyword> ist ebenfalls vom Typ anyURI und enthält die Adresse, unter der die zu signierenden Daten verfügbar sind. Die Daten, auf die sich die digitale Signatur bezieht, müssen nicht im <link id="signatures_syntax_signature.html">Signature</link> Element selbst vorhanden sein, sondern können auch über das lokale Dateisystem oder eine Internet-Adresse referenziert werden. Enthält das Attribut also eine Webadresse handelt es sich um eine <link id="signatures_detached.html">detached signature</link>.</p>		<p>Daneben gibt es noch URIs, die auf das aktuelle Dokument verweisen wie z.B. <keyword>URI=&quot;&quot;</keyword>. Dieser spezielle Uniform Resource Identifier steht für alle XML-Knoten des aktuellen XML-Dokuments, jedoch ohne die möglicherweise vorhandenen Kommentare. Die zur Signatur gehörenden Knoten sind in der Auswahl jedoch enthalten.</p>		<p>Auch das gezielte Auswählen von Teildokumenten (<keyword>fragment identifier</keyword>) oder Elementen ist mittels XPointer und XPath möglich. Werden mehrere <strong>Reference</strong> Elemente angegeben darf das <keyword>URI</keyword> Attribut nur bei einem ausgelassen werden. In diesem Fall ist die Applikation dafür zuständig, die zu signierenden Daten zu bestimmen.</p>		<p>Reference besitzt drei Kindelemente: <link id="signatures_syntax_signedinfo.html#Transforms">Transforms</link> (optional) sowie die Pflichtelemente <link id="signatures_syntax_signedinfo.html#DigestMethod">DigestMethod</link> und <link id="signatures_syntax_signedinfo.html#DigestValue">DigestValue</link>.</p>		<headline id="Transforms">Transforms</headline>		<p>Wird das optionale Element <strong>Transforms</strong> angegeben, so durchlaufen die referenzierten Daten zunächst der Reihe nach sämtliche in den <strong>Transform</strong> Kindelementen aufgeführten Transformationen. Der Hashwert wird vom Ergebnis der letzten Transformation berechnet, die Reihenfolge der Transformationen ist also von Bedeutung. In dem Fall wird damit nicht das ursprüngliche, sondern das transformierte Dokument(fragment) signiert. Fehlt das <strong>Transforms</strong> Element wird der Hashwert vom gesamten referenzierten Objekt berechnet.</p>		<p>Jedes <strong>Transforms</strong> Element besteht dazu aus einem <keyword>Algorithm</keyword> Attribut mit dem anzuwendenden <link id="signatures_transform.html">Transformations-Algorithmus</link>.</p>		<headline id="DigestMethod">DigestMethod</headline>		<p>Das leere Pflichtelement <strong>DigestMethod</strong> enthält im <keyword>Algorithm</keyword> Attribut ausschließlich einen URI zur Identifikation des Message Digest Algorithmus. Der URI kann die in der folgenden Tabelle aufgeführten Werte annehmen.</p>		<table>			<head>				<data>Name</data>				<data>URI</data>				<data>Implementierung</data>			</head>			<row>				<data>					<strong>MD5</strong>				</data>				<data>http://www.w3.org/2000/09/xmldsig#md5</data>				<data>nicht empfohlen</data>			</row>			<row>				<data>					<strong>SHA 1</strong>				</data>				<data>http://www.w3.org/2000/09/xmldsig#sha1</data>				<data>erforderlich</data>			</row>		</table>		<headline id="DigestValue">DigestValue</headline>		<p>Mit dem in <link id="signatures_syntax_signedinfo.html#DigestMethod">DigestMethod</link> angegebenen Algorithmus wird der <strong>DigestValue</strong>, ein eindeutiger Hashwert des signierten Objekts, berechnet und per Base-64 encoding in diesem Element gespeichert. Der Hashwert, der auch als digitaler Fingerabdruck bezeichnet werden kann, ist meist kürzer als die signierten Daten und kann somit im folgenden Schritt schneller signiert werden. Es ist praktisch unmöglich, aus einem gegebenen Hashwert die ursprüngliche Nachricht zu ermitteln. Außerdem sollte es unmöglich sein, dass zwei beliebige Nachrichten denselben Hashwert ergeben (Kollision und Geburtstagsparadoxon).</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/signatures_transform.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="signatures_transform" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Transformation</title>	<text>		<p>Mittels Transformationen können die durch das URI Attribut adressierten Daten vor der Hashwertberechnung umgewandelt und gezielt Dokumentfragmente zum Signieren ausgewählt werden.</p>		<p>			<strong>Base64</strong> wandelt Base-64 Zeichenketten zurück in die entsprechenden Oktette. Base-64 ist ein von der IETF spezifiziertes Kodierungsverfahren für Binärdaten und ermöglicht die Einbettung beliebiger Daten in das XML-Dokument. Der Name Base-64 kommt daher, dass zur Kodierung von Daten aller Art nur die 64 Zeichen <keyword>a-z, A-Z, 0-9,+,/</keyword> verwendet werden. Binäre Zeichen könnten sonst nicht in XML dargestellt werden. Die so eingebetteten Binärdaten werden im Base-64 encoding dadurch allerdings um 33% größer als die Ursprungsdaten im Binärformat.</p>		<p>Die <strong>Enveloped Signature Transform</strong> verhindert, dass Signaturen sich selbst signieren, indem vor dem Signieren alle zur Signatur gehörenden Elemente durch die Transformation entfernt werden.</p>		<p>Das <strong>XPath Filtering</strong> verarbeitet XPath-Knoten. Mit diesen Transformationen können Knoten aus einer XML-Knotenmenge ausgewählt werden, die beim Signieren berücksichtigt werden sollen. Der Rest des Dokuments wird nicht in die Signatur miteinbezogen. Wird XPath als Transformation einer XML-Signatur verwendet, wird es als Filtermechanismus angewandt und nicht als Auswahlmechanismus. Der XPath Filter 2.0 besitzt die gleichen Funktionen wie die ursprünglichen XPath Transformationen, arbeitet aber sehr viel effizienter und besitzt eine einfachere Syntax.</p>		<p>Eine <strong>XSLT Transform</strong> transformiert die zu signierenden Daten mit den Extensible Stylesheet Language Transformations (XSLT). Mit XSLT können die XML-Daten beispielsweise vor dem Signieren in die HyperText Markup Language (HTML) umgewandelt werden.</p>		<p>Möglich sind die in der folgenden Tabelle aufgeführten Transformationen. Zusätzlich zu den hier aufgeführten Algorithmen gehören auch die bereits bei der <link id="signatures_canon.html">Kanonisierung</link> genannten Algorithmen zu den Transformationen.</p>		<table>			<head>				<data>Name</data>				<data>URI</data>				<data>Implementierung</data>			</head>			<row>				<data>					<strong>Base64</strong>				</data>				<data>http://www.w3.org/2000/09/xmldsig#base64</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>Enveloped Signature Transform</strong>				</data>				<data>http://www.w3.org/2000/09/xmldsig#enveloped-signature</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>XPath Filtering</strong>				</data>				<data>http://www.w3.org/TR/1999/REC-xpath-19991116</data>				<data>empfohlen</data>			</row>			<row>				<data>					<strong>XSLT Transform</strong>				</data>				<data>http://www.w3.org/TR/1999/REC-xslt-19991116</data>				<data>optional</data>			</row>		</table>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/signatures_detached.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="signatures_detached" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Detached Signature</title>	<text>		<p>Bei einer <strong>detached signature</strong> gibt es keine Eltern-Kind-Beziehung zwischen Signatur und Dokument. Das Originaldokument ist vielmehr eine separate Ressource. Das zu signierende Dokument wird bei einer <strong>detached signature</strong> nicht verÃ¤ndert. Der signierte Inhalt kann sich im selben Dokument wie die Signatur oder in einem anderen Dokument befinden.</p>		<image id="../images/signatures_detached.png" title="Detached Signature" width="425" height="284"/>		<p>Der XML-Baum hat damit den folgenden Aufbau:</p>		<code>&lt;Signature&gt;&lt;/Signature&gt;&lt;DocumentData&gt;&lt;/DocumentData&gt;</code>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/signatures_canon.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="signatures_canon" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Kanonisierung</title>	<text>		<p>Trotz logischer Gleichheit der reinen Dokumentdaten lassen sich Veränderungen am physischen Dokument durch die Verarbeitung, beispielsweise auf verschiedenen Plattformen oder in unterschiedlichen Editoren/ Anwendungen, nicht verhindern. Um ungültige Signaturen auszuschließen, wird daher vor dem Signieren ein Kanonisierungs-Algorithmus auf das wohlgeformte XML-Dokument angewandt. Hiermit werden syntaktische Unterschiede - wie beispielsweise der Zeichensatz, Zeilenumbrüche, leere Tags und die Reihenfolge der Attribute - von ansonsten semantisch identischen XML-Dokumenten kanonisiert. Eine andere Bezeichnung für Kanonisierung ist Normalisierung. Der Kanonisierungs-Algorithmus stellt dabei sicher, dass immer dieselben Bytes in die Hashwertberechnung einfließen und anschließend signiert werden. Die bei digitalen Signaturen zahlreich vorhandenen URIs werden jedoch niemals kanonisiert.</p>		<p>Auffällig ist, dass zwar die XML-Deklaration zur Kanonisierung herangezogen wird, diese Deklaration im kanonisierten XML-Dokument aber nicht mehr enthalten ist. Das ist nur konsequent, die Angabe des <keyword>encodings</keyword> ist überflüssig da ein kanonisches XML-Dokument immer in einer <keyword>UTF-8</keyword> Kodierung vorliegt und eine fehlende Versionsangabe immer XML Version 1.0 bedeutet. Das erfordert allerdings, dass bei einer neuen XML-Version auch die Kanonisierung überarbeitet wird.</p>		<p>			<strong>Beim Kanonisieren eines XML-Dokuments finden die folgenden Aktionen statt:</strong>		</p>		<list type="unordered">			<point>Das Dokument wird in UTF-8 kodiert</point>			<point>Zeilenumbrüche werden vor dem Parsen normalisiert zu #xA</point>			<point>Attributwerte werden normalisiert (wie bei einem validierenden Parser)</point>			<point>Character- und parsed-entity Referenzen werden ersetzt</point>			<point>CDATA Abschnitte werden durch ihren Inhalt ersetzt</point>			<point>Die XML-Deklaration und eine möglicherweise vorhandene DTD werden entfernt</point>			<point>Leere Elemente werden zu Start-End-Tag Paaren umgewandelt</point>			<point>Whitespace außerhalb des Dokumentelements und innerhalb von Start- und End-Tags wird normalisiert</point>			<point>Whitespace in Textknoten wird beibehalten (gilt jedoch nicht für Zeichen die bei der Normalisierung der Zeilenumbrüche entfernt wurden)</point>			<point>Attributwerte werden in doppelten Anführungsstrichen eingeschlossen</point>			<point>Sonderzeichen in Attributwerten und Textknoten werden durch Zeichenreferenzen ersetzt</point>			<point>Überflüssige Namespace Deklarationen werden von jedem Element entfernt</point>			<point>Defaultattribute werden zu den jeweiligen Elementen hinzugefügt</point>			<point>Namespace Deklarationen und Attribute werden alphanumerisch sortiert</point>		</list>		<p>Zu kanonischem XML existieren seit 15. März 2001, 18. Juli 2002 bzw. 29. Januar 2008 drei Empfehlungen des W3C: <keyword>Canonical XML 1.0 (C14N 1.0)</keyword>, <keyword>Canonical XML 1.1 (C14N 1.1)</keyword> und <keyword>Exclusive XML Canonicalization 1.0</keyword>. Drei Empfehlungen, die alle mehr oder weniger das Gleiche tun...</p>		<p>Nun ja, es gibt einige Unterschiede: So wird die <keyword>exclusive</keyword> Variante unter anderem für Protokolle wie SOAP und damit Web Services benötigt und sollte auch in Zusammenhang mit <strong>xml:id</strong> verwendet werden. Mit der gebräuchlicheren <keyword>Exclusive XML Canonicalization 1.0</keyword> wird ein XML-Dokument soweit wie möglich ohne den dazugehörigen Kontext (d.h. Namensräume der Vorfahren) normalisiert. Damit wird eine digitale Signatur auch nicht ungültig falls ein kanonisiertes Dokumentfragment aus dem Kontext entfernt und/ oder in ein anderes XML-Dokument eingefügt wird.</p>		<p>Alternativ kann bei Verwendung von <strong>xml:id</strong> oder <strong>xml:base</strong> Attributen auch die aktualisierte <keyword>Canonical XML 1.1</keyword> Empfehlung angewendet werden, mit <keyword>Canonical XML 1.0</keyword> gibt es hier Probleme. <keyword>Canonical XML 1.0</keyword> und <keyword>Canonical XML 1.1</keyword> machen jedoch prinzipiell dasselbe, die Verwendung der aktualisierten Version 1.1 wird aber empfohlen. Es wurde weiter oben schon angesprochen, bei der Kanonisierung von Dokumentfragmenten kann der übergeordnete Kontext verloren gehen. Damit das XML-Dokument z.B. durch eine nach der Kanonisierung fehlende Namespace Deklaration nicht ungültig wird, werden Attribute kopiert. Auch solche im xml Namespace wie z.B. <strong>xml:base</strong> und <strong>xml:id</strong>. Und mit diesen beiden gibt es Probleme. Während bei <strong>xml:base</strong> einfach auch der Attributwert (d.h. der darin enthaltene Pfad) angepasst werden muss, ist das Kopieren von <strong>xml:id</strong> schlichtweg falsch. <strong>xml:id</strong> ist eine Empfehlung vom September 2005 und beschreibt kurz gesagt eine Möglichkeit, Elemente mit eindeutigen IDs auszustatten. Eine ID muss eindeutig sein, nach dem Kopieren ist das aber nicht mehr der Fall. C14N 1.1 wurde dahingehend erweitert, dass <strong>xml:base</strong> Attribute angepasst werden und <strong>xml:id</strong> nicht kopiert, d.h. nicht in den Kontext eines Subdokuments übernommen werden. Bei der Verwendung von C14N 1.0 können hier <keyword>xml:id errors</keyword> auftreten. Das sind zwar keine fatalen Fehler, d.h. das XML-Dokument kann weiterverarbeitet werden, trotzdem kann das XML-Dokument später unbrauchbar sein.</p>		<p>Die <keyword>Exclusive XML Canonicalization 1.0</keyword> und auch <keyword>Canonical XML 1.1</keyword> weisen dieses Feature (es handelt sich tatsächlich ein Feature und kein Bug) nicht auf, daher sollte bei XML-Dokumenten mit <strong>xml:id</strong> Attributen besser auf einen dieser Kanonisierungs-Algorithmen zurückgegriffen werden.</p>		<p>Canonical XML 1.1 ist übrigens, auch wenn es der Name andeuten mag, nicht für XML 1.1 geeignet. Für XML 1.1 steht noch keine Kanonisierungsmöglichkeit zur Verfügung; XML Digitale Signaturen können daher mit XML 1.1 derzeit nicht verwendet werden. Mangels Rückwärtskompatibilität wird XML 1.1 wohl ohnehin nur für wenige Anwendungsgebiete und Entwickler interessant sein, daher lässt sich das wohl verschmerzen. Elliotte Rusty Harold empfiehlt XML 1.1 ohnehin nur einer eingeschränkten Zielgruppe: <keyword>&quot;XML 1.1 has a number of new features that make it much more suitable for use by IBM mainframe programmers and people whose native language is Amharic, Burmese, or Cambodian.&quot;</keyword>. Alle anderen können ohne schlechtes Gewissen auch weiterhin XML 1.0 verwenden.</p>		<p>Aber ganz egal welche Kanonisierung verwendet wird, es stehen immer jeweils zwei Möglichkeiten zur Kanonisierung zur Verfügung. Bei der einen Version werden die Kommentare im kanonisierten XML-Dokument entfernt (<keyword>canonical XML omits comments</keyword>), bei der anderen Version bleiben die Kommentare erhalten (<keyword>canonical XML with comments</keyword>). Auch bei der Kanonisierung ist es möglich, nur XML-Dokumentfragmente zu kanonisieren und die restlichen Dokumentteile in ihrer ursprünglichen Form zu belassen. Im Gegensatz zum vollständigen Kanonisieren eines XML-Dokuments kann es bei einer XML-Dokument Untermenge (<keyword>document subset</keyword>) durchaus vorkommen, dass das resultierende XML-Dokument nicht mehr wohlgeformt ist.</p>		<p>Die vorhandenen Kanonisierungs-Algorithmen und die zugehörigen Uniform Resource Identifier zeigt die folgende Tabelle. Identifiziert wird der gewünschte Algorithmus immer über den jeweiligen URI.</p>		<table>			<head>				<data>Name</data>				<data>URI</data>				<data>Implementierung</data>			</head>			<row>				<data>					<strong>Canonical XML 1.0</strong>				</data>				<data>http://www.w3.org/TR/2001/REC-xml-c14n-20010315</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>Canonical XML 1.0 with Comments</strong>				</data>				<data>http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments</data>				<data>empfohlen</data>			</row>			<row>				<data>					<strong>Canonical XML 1.1</strong>				</data>				<data>http://www.w3.org/2006/12/xml-c14n11</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>Canonical XML 1.1 with Comments</strong>				</data>				<data>http://www.w3.org/2006/12/xml-c14n11#WithComments</data>				<data>empfohlen</data>			</row>			<row>				<data>					<strong>Exclusive XML Canonicalization 1.0</strong>				</data>				<data>http://www.w3.org/2001/10/xml-exc-c14n#</data>				<data>optional</data>			</row>			<row>				<data>					<strong>Exclusive XML Canonicalization 1.0 with Comments</strong>				</data>				<data>http://www.w3.org/2001/10/xml-exc-c14n#WithComments</data>				<data>optional</data>			</row>		</table>	</text></chapter>
