=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/resources/documentation.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.xml-sicherheit.de" targetNamespace="http://www.xml-sicherheit.de" xml:lang="en">	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>	<xs:annotation>		<xs:documentation xml:lang="en">			XML-Security Plug-in documentation schema. Used for online help and tutorials.		</xs:documentation>	</xs:annotation>	<xs:element name="title" type="xs:string"/>	<xs:element name="strong" type="xs:string"/>	<xs:element name="keyword" type="xs:string"/>	<xs:element name="definition" type="xs:string"/>	<xs:element name="description" type="xs:string"/>	<xs:element name="headline">		<xs:complexType>			<xs:simpleContent>				<xs:extension base="xs:string">					<xs:attribute name="id" type="xs:ID" use="required"/>				</xs:extension>			</xs:simpleContent>		</xs:complexType>	</xs:element>	<xs:element name="data">		<xs:complexType mixed="true">			<xs:sequence>				<xs:element ref="strong" minOccurs="0" maxOccurs="unbounded"/>				<xs:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="acronyms">		<xs:complexType>			<xs:sequence>				<xs:element ref="acronym" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="acronym">		<xs:complexType>			<xs:sequence>				<xs:element ref="definition"/>				<xs:element ref="description"/>			</xs:sequence>			<xs:attribute name="abbreviation" type="xs:ID" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="chapter">		<xs:complexType>			<xs:sequence>				<xs:element ref="title" minOccurs="0"/>				<xs:element ref="text"/>			</xs:sequence>			<xs:attribute name="category" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="general"/>						<xs:enumeration value="basics"/>						<xs:enumeration value="plugin"/>						<xs:enumeration value="resources"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute ref="xml:lang" use="required"/>			<xs:attribute ref="xml:id" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="text">		<xs:complexType>			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="p"/>				<xs:element ref="list"/>				<xs:element ref="code"/>				<xs:element ref="table"/>				<xs:element ref="headline"/>				<xs:element ref="link"/>				<xs:element ref="image"/>				<xs:element ref="resources" minOccurs="0"/>				<xs:element ref="acronyms" minOccurs="0"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="p">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="strong"/>				<xs:element ref="keyword"/>				<xs:element ref="link"/>				<xs:element ref="eclipse"/>			</xs:choice>			<xs:attribute name="id" type="xs:ID" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="list">		<xs:complexType>			<xs:choice maxOccurs="unbounded">				<xs:element ref="point"/>				<xs:element ref="list"/>			</xs:choice>			<xs:attribute name="type" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="ordered"/>						<xs:enumeration value="unordered"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="point">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="strong"/>				<xs:element ref="keyword"/>				<xs:element ref="link"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="link">		<xs:complexType mixed="true">			<xs:sequence>				<xs:element ref="image" minOccurs="0"/>			</xs:sequence>			<xs:attribute name="id" type="xs:anyURI" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="image">		<xs:complexType>			<xs:attribute name="id" type="xs:anyURI" use="required"/>			<xs:attribute name="title" type="xs:string" use="required"/>			<xs:attribute name="width" use="required">				<xs:simpleType>					<xs:restriction base="xs:positiveInteger">						<xs:minInclusive value="1"/>						<xs:maxInclusive value="800"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute name="height" use="required">				<xs:simpleType>					<xs:restriction base="xs:positiveInteger">						<xs:minInclusive value="1"/>						<xs:maxInclusive value="800"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="table">		<xs:complexType>			<xs:sequence>				<xs:element ref="head"/>				<xs:element ref="row" maxOccurs="unbounded"/>			</xs:sequence>			<xs:attribute name="width" type="xs:positiveInteger" use="optional"/>			<xs:attribute name="border" type="xs:positiveInteger" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="head">		<xs:complexType>			<xs:sequence>				<xs:element ref="data" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="row">		<xs:complexType>			<xs:sequence>				<xs:element ref="data" maxOccurs="unbounded"/>			</xs:sequence>			<xs:attribute name="valign" type="xs:string" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="resources">		<xs:complexType>			<xs:sequence>				<xs:element ref="title"/>				<xs:element ref="link" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="code">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="link"/>			</xs:choice>		</xs:complexType>	</xs:element></xs:schema>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/encryption_syntax_encryptionmethod.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="encryption_syntax_encryptionmethod" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Das EncryptionMethod Element</title>	<text>		<p>Das optionale Element <strong>EncryptionMethod</strong> bestimmt mit dem Attribut <keyword>Algorithm</keyword> den verwendeten Verschlüsselungsalgorithmus und mögliche zugehörige Parameter. Fehlt dieses Element muss dem Empfänger oder der verarbeitenden Applikation der zur Verschlüsselung verwendete Algorithmus bekannt sein.</p>		<p>Zwei der möglichen Kindelemente sind <strong>KeySize</strong> und <strong>OAEPparams</strong> die den verwendeten Algorithmus durch Angabe der Schlüssellänge und weiterer Parameter näher beschreiben. Welche Kindelemente jeweils erlaubt bzw. erforderlich sind hängt vom gewählten Algorithmus ab der über das <keyword>Algorithm</keyword> Attribut bestimmt wird.</p>		<p>Das <keyword>Algorithm</keyword> Attribut der <strong>EncryptionMethod</strong> kann u.a. die in der folgenden Tabelle aufgeführten URIs annehmen.</p>		<table>			<head>				<data>Name</data>				<data>URI</data>				<data>Implementierung</data>			</head>			<row>				<data>					<strong>AES 128</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#aes128-cbc</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>AES 192</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#aes192-cbc</data>				<data>optional</data>			</row>			<row>				<data>					<strong>AES 256</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#aes256-cbc</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>TRIPLEDES</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#tripledes-cbc</data>				<data>erforderlich</data>			</row>		</table>		<p>Zum Kodieren von geheimen Schlüsseln dienen die symmetrischen Algorithmen mit dem Zusatz <keyword>Key Wrap</keyword> in der folgenden Tabelle. <strong>EncryptionMethod</strong> muss dazu ein Kindelement von <link id="encryption_syntax_keyinfo.html#EncryptedKey">EncryptedKey</link> sein.</p>		<table>			<head>				<data>Name</data>				<data>URI</data>				<data>Implementierung</data>			</head>			<row>				<data>					<strong>AES-128 Key Wrap</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#kw-aes128</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>AES-192 Key Wrap</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#kw-aes192</data>				<data>optional</data>			</row>			<row>				<data>					<strong>AES-256 Key Wrap</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#kw-aes256</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>TRIPLEDES Key Wrap</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#kw-tripledes</data>				<data>erforderlich</data>			</row>		</table>		<p>Die RSA Algorithmen <keyword>RSA-v1.5</keyword> und <keyword>RSA-OAEP</keyword> sind asymmetrische Algorithmen zum sicheren Schlüsseltransport. Diese Algorithmen können nur verwendet werden, wenn <strong>EncryptionMethod</strong> ein Kindelement von <link id="encryption_syntax_keyinfo.html#EncryptedKey">EncryptedKey</link> ist.</p>		<table>			<head>				<data>Name</data>				<data>URI</data>				<data>Implementierung</data>			</head>			<row>				<data>					<strong>RSA-v1.5</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#rsa-1\_5</data>				<data>erforderlich</data>			</row>			<row>				<data>					<strong>RSA-OAEP</strong>				</data>				<data>http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p</data>				<data>erforderlich</data>			</row>		</table>		<p>Prinzipiell können beliebige weitere Algorithmen verwendet werden. Dies ist von der konkreten Implementierung abhängig. Die Empfehlung des W3C lässt dabei offen, ob symmetrische oder asymmetrische Algorithmen verwendet werden.</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/signatures_syntax_signature.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="signatures_syntax_signature" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Das Signature Element</title>	<text>		<p>Das Wurzelelement einer digitalen Signatur mit XML wird durch das Element <strong>Signature</strong> dargestellt.</p>		<p>			<strong>Signature</strong> besitzt ein optionales Attribut <keyword>Id</keyword> vom Typ ID zur Identifikation der Signatur. Dieses Attribut ermöglicht die Identifikation einer bestimmten Signatur, falls ein XML-Dokument mehrere Signaturen enthält. Des Weiteren deklariert das Element den Namensraum (<keyword>namespace</keyword>) der Signatur mit dem Attribut <keyword>xmlns</keyword>. Das Namensraum Attribut kennzeichnet gleichzeitig auch die Version der XML-Signatur, eine Versionsangabe wie beispielsweise bei den XSL Transformations ist daher nicht notwendig. Derzeit gibt es für den Namensraum einen einzigen Wert: <keyword>http://www.w3.org/2000/09/xmldsig#</keyword> der an das Präfix <keyword>ds</keyword> gebunden wird. Neuere Versionen der Empfehlung werden einen anderen Namensraum verwenden.</p>		<p>			<strong>Signature</strong> besitzt vier Kindelemente, wovon die beiden Elemente <link id="signatures_syntax_signedinfo.html">SignedInfo</link> und <link id="signatures_syntax_signaturevalue.html">SignatureValue</link> Pflicht sind. Des Weiteren kann ein <link id="signatures_syntax_keyinfo.html">KeyInfo</link> Element angegeben werden sowie beliebig viele <link id="signatures_syntax_object.html">Object</link> Elemente (auch null). Im Minimalfall besteht die XML-Signatur somit nur aus den Elementen <link id="signatures_syntax_signedinfo.html">SignedInfo</link> und <link id="signatures_syntax_signaturevalue.html">SignatureValue</link>.</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/plugin/cheatsheets.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="plugin" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="cheatsheets" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Cheat Sheets</title>	<text>		<p>Die <strong>Cheat Sheets</strong> sind deutsch- bzw. englischsprachige Tutorials (die angezeigte Sprache hängt von den Ländereinstellungen des Betriebssystems ab) speziell für Anfänger und sollen Ihnen den Einstieg in das XML-Security Plug-In und die XML-Sicherheit erleichtern. Mit den fünf verfügbaren Anleitungen werden Sie Schritt für Schritt durch die Generierung einer <link id="sign.html">digitalen Signatur</link>, die <link id="verify.html">Verifizierung</link> sowie <link id="encrypt.html">Ver-</link> und <link id="decrypt.html">Entschlüsselung</link> und die Verwendung der <link id="quick.html">Quick Functions</link> geführt.</p>		<p>Anzeigen können Sie die Cheat Sheets über den Menüpunkt <keyword>Cheat Sheets...</keyword> im Menü <keyword>Help</keyword>. Im sich öffnenden Fenster finden Sie eine Rubrik <keyword>XML Security</keyword> mit den fünf enthaltenen Cheat Sheets. Nach der Auswahl eines Tutorials und dem Klick auf <strong>OK</strong> wird die gewünschte Anleitung angezeigt und Sie können diese schrittweise durcharbeiten. Über die Hilfe-Icons neben jedem Eintrag gelangen Sie zu weiterführenden Informationen in der Online-Hilfe.</p>		<p>Einige Abschnitte besitzen Icons zum Starten einer Aktion. Beispielsweise können Sie sich in den Signatur- und Verschlüsselungs-Cheat Sheets ein Projekt und ein XML-Dokument zum Ausprobieren generieren lassen. Außerdem können Sie direkt von aus dem <keyword>Quick Functions</keyword> Cheat Sheet in die Preferences Ihres Workspace wechseln.</p>		<p>Selbstverständlich können Sie einzelne Schritte überspringen sofern Sie die darin enthaltenen Aktionen bereits durchgeführt haben (wenn Sie z.B. bereits ein XML-Dokument zum Sichern erstellt haben).</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/plugin/sign_page_open_key.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="plugin" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="sign_page_open_certificate" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Open an existing Key</title>	<text>		<p>Auf dieser zweiten Seite des <keyword>Digital Signature Wizard</keyword> müssen Sie zunächst den gewünschten Keystore und ein darin enthaltenes Zertifikat auswählen sowie die zugehörigen Passwörter angeben.</p>		<image id="../images/dsig-2a.png" title="Open an existing Certificate" width="275" height="392"/>		<p>Zunächst müssen Sie eine Java Keystore Datei (mit der Dateiendung <keyword>.jks</keyword>) auswählen. Über den Button <strong>Open...</strong> öffnen Sie das Standarddialogfeld zur Auswahl einer solchen Datei.</p>		<p>Anschließend sind weitere Angaben zum Keystore und Zertifikat erforderlich. Alle angegebenen Felder sind Pflichtfelder. Mit den <strong>Punkt</strong> Buttons rechts neben den Passwortfeldern können sie den Klartext in einem Passwortfeld anzeigen lassen und Ihre Eingabe kontrollieren.</p>		<p>Mit dem <keyword>Keystore Password</keyword> kann der Keystore selbst geöffnet werden. Anschließend legen Sie mit dem <keyword>Certificate Alias</keyword> fest, welches Zertifikat aus dem Keystore geladen werden soll. Dieses Zertifikat wird zur Erzeugung des <link id="../basics/signatures_syntax_keyinfo.html">KeyInfo</link> Elements und später zur <link id="verify.html">Verification</link> der Signatur benötigt. Eine Signatur lässt sich zwar auch ohne Angabe des <keyword>Certificate Alias</keyword> erzeugen, kann dann aber nicht mit dem XML-Security Plug-In verifiziert werden. Die Angabe des Alias ist daher ebenfalls erforderlich. Zum Abschluss müssen Sie noch das Passwort des Zertifikats angeben.</p>		<p>Nach der korrekten Eingabe aller erforderlichen Daten können Sie mit dem <strong>Next</strong> Button auf die nächste Seite des Digital Signature Wizards wechseln: <link id="sign_page_algorithms.html">Algorithms and Signature Properties</link>.</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/sample_encrypted.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?>
<chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="sample_encrypted" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">
	<title>Beispiel - Verschl체sselt</title>
	<text>
		<p>Die folgenden Beispiele zeigen die zwei <link id="encryption_syntax_cipherdata.html">Verschl체sselungsvarianten</link> im von oben bekanntem <link id="sample.html">Beispiel XML-Dokument</link>. Zur 체bersichtlicheren Darstellung wurden alle Beispiele nachtr채glich formatiert.</p>
		<headline id="envelopingEncryption">Enveloping Encryption</headline>
		<code>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;xenc:EncryptedData xmlns:xenc=&quot;http://www.w3.org/2001/04/xmlenc#&quot;
 Id=&quot;enveloping-sample&quot; Type=&quot;http://www.w3.org/2001/04/xmlenc#Element&quot;&gt;
 &lt;xenc:EncryptionMethod Algorithm=&quot;http://www.w3.org/2001/04/xmlenc#aes256-cbc&quot;/&gt;
 &lt;ds:KeyInfo xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
  &lt;xenc:EncryptedKey&gt;
   &lt;xenc:EncryptionMethod Algorithm=&quot;http://www.w3.org/2001/04/xmlenc#kw-aes128&quot;/&gt;
   &lt;xenc:CipherData&gt;
    &lt;xenc:CipherValue&gt;rojIk5KAKQLdxwsvNzKL1slqdrAbvhQa&lt;/xenc:CipherValue&gt;
   &lt;/xenc:CipherData&gt;
  &lt;/xenc:EncryptedKey&gt;
 &lt;/ds:KeyInfo&gt;
 &lt;xenc:CipherData&gt;
  &lt;xenc:CipherValue&gt;
   IxZg5/ybM3tKnRK7krng3YE+GmosiCY7u1ZJB3s7LoTDf4KvGnSTh+CUQ50g5lz2SnRFgUj4PpxG
   4EBX6MOPWG7Idx+JlzOx0+PCnVLU7JNIYi8MXGKtmj3yxtFr6Lx9kT6lPPqoorhWm/jaQqsdRhMc
   XbLQLRMfY2ZqckcLpd7w55K8iMu5P8w1l4RRV4tw0XLI3TDj++204NFiBzyd5joVyDfCibuP+UXs
   ArtPsGVGoF5zIy/1d9dW96hTpiLIeU82mYCLF3d+2dLAGi0Gd4Awp3eoYKPti9l60r3NqMfZIW+s
   5oDzUc3b7DrtXUYEp4oxb5CXdWuVdnStFG03uBOgMqk189EZaBUZWpx0wabxAs3yHQktFIKsIHKk
   a4MOK9dHCiqc7ja/CHDUKAhCyrg+H5xE5E60+p0JYnWUovax+wa/x+QnbjYH9JyV9+41H7wpb3pA
   0ONHyrciJbQtZJKLvkMGOv7Q1Qx1TjM4PPiUqs71KyizqJ40Y8yG4bBlUD/2T+eyCXN1iLHZwInQ
   SUqceU094kAtQA5IErwUh/yZlVFw90H5gVeyhddQhXb2ggQ4ENyLSWY/tgdsE0qPz7Z2bU06wmOs
   Tj1cQUCQIiCuoGu9DqF16uExNtZ/QPwHTeFiUmCwOLi7blPPlFzz2P2r9GjJFVTrNSAODLUE7wRE
   j+qLyIO8sUBHrl6BeDwBcGdHtmuLeTh4uSrCORib8l65Djr+pmCo0/LPHwBhH4s2o1tU1Kcvde4Q
   Fpt3jtBsAxARueRSBqg0PqR8GDerBu6tS8FvsGDz1D4IwwY/Xq3SD0ew4XLQc2vcSMKN5hRSuYDm
   5jEPNpy0JEXYn94OarnnfMfvHEATFi9nX/egmc8kmLXFMB5B6R9GD6SCuNcnyqvX+VM+v98yy3mb
   ub2XOeshOnhqox3DA5r/7LXLv6BOYWWqpNjFJEOoPizOow4NQLzd5SpbHY7FJhuDkMkYrWLJGg3B
   x/JMueEGmYOPuutVTh9m9L8bbWFflE+/etTs+ZYvl9rt4rcXJxK6Dk06hUMgzEpFNjFHCY84bbYp
   Zkk/31x6BxhJgmAPR+E5e0cZUuqzG2Q2FNgAMt+OpOUHtWi8EPp8Am2GMlUOs3hJH/+4g9gz6WiI
   ZZFT3e35OGyadFEQNiobzBCTbp9ymu7U+A9WAohXFg0jlRGWVUPFHByjw7QKqyGJIlSPJSyfeG1j
   U+Gcbrb9Zy4Jv/cwgYVx9zJNbnlURbtVBt5+996YTtcIOcVRKNuxozUI8H8Q8KO7
  &lt;/xenc:CipherValue&gt;
 &lt;/xenc:CipherData&gt;
&lt;/xenc:EncryptedData&gt;
</code>
		<headline id="detachedEncryption">Detached Encryption</headline>
		<code>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;xenc:EncryptedData xmlns:xenc=&quot;http://www.w3.org/2001/04/xmlenc#&quot;
 Id=&quot;detached-sample&quot; Type=&quot;http://www.w3.org/2001/04/xmlenc#Element&quot;&gt;
 &lt;xenc:EncryptionMethod Algorithm=&quot;http://www.w3.org/2001/04/xmlenc#tripledes-cbc&quot;/&gt;
 &lt;ds:KeyInfo xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
  &lt;xenc:EncryptedKey&gt;
   &lt;xenc:EncryptionMethod Algorithm=&quot;http://www.w3.org/2001/04/xmlenc#kw-tripledes&quot;/&gt;
   &lt;xenc:CipherData&gt;
    &lt;xenc:CipherValue&gt;8PSWTVBjn4m5Q0fDV2Q4c6FZ2BigxoCi&lt;/xenc:CipherValue&gt;
   &lt;/xenc:CipherData&gt;
  &lt;/xenc:EncryptedKey&gt;
 &lt;/ds:KeyInfo&gt;
 &lt;xenc:CipherData&gt;
  &lt;xenc:CipherReference URI=&quot;invoice.xml&quot;/&gt;
 &lt;/xenc:CipherData&gt;
&lt;/xenc:EncryptedData&gt;
</code>
		<p>Das Beispiel <link id="sample_signed.html">signiert</link> (<link id="sample_signed.html#envelopedSignature">enveloped</link>, <link id="sample_signed.html#envelopingSignature">enveloping</link>, <link id="sample_signed.html#detachedSignature">detached</link>) oder im <link id="sample.html">Original</link>.</p>
	</text>
</chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/basics/signatures_canon_transform.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="basics" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="signatures_canon_transform" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Kanonisierung und Transformation</title>	<text>		<p>Zwei Begriffen kommen bei der digitalen Signatur mit XML eine große Bedeutung zu: Kanonisierung (<keyword>canonicalization</keyword>, auch <keyword>C14N</keyword>) und Transformation (<keyword>transformation</keyword>). C14N übrigens deshalb, weil zwischen dem ersten Buchstaben C und dem letzten n von Canonicalization genau 14 weitere Buchstaben stehen.</p>		<p>Bei der <link id="signatures_canon.html">Kanonisierung</link> eines XML-Dokuments wird dieses in einheitlicher Form in einen Bytestrom überführt. Kanonisierung steht somit für die Normalisierung von XML-Dokumenten, um robuste und sichere Signaturen zu ermöglichen. Neben dem Einsatz in digitalen Signaturen ist die Kanonisierung beispielsweise auch wichtig bei der XML-basierten Versionskontrolle (d.h. beim <keyword>diff</keyword>).</p>		<p>Mit <link id="signatures_transform.html">Transformationen</link> beschreibt XML die Umwandlung von referenzierten Daten vor der Signierung auf verschiedenste Art und Weise.</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/plugin/decrypt.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="plugin" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="decrypt" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Decryption Wizard</title>	<text>		<p>Mit dem <keyword>Decryption Wizard</keyword> können Sie auf komfortable und einfache Weise Ihre verschlüsselten XML-Dokumente wieder entschlüsseln und den Klartext wiederherstellen. Hierfür benötigen Sie die bei der <link id="encrypt.html">Verschlüsselung</link> gespeicherte Datei mit dem Schlüssel und den für diese Datei gewählten Verschlüsselungsalgorithmus.</p>		<p>Der <keyword>Decryption Wizard</keyword> wird über den Eintrag <strong>New Decryption...</strong> im Kontextmenü aufgerufen. Er besteht aus einer einzigen Seite <link id="decrypt_page_decryption.html">Decryption</link>. Über das Hilfe-Icon links unten auf jeder Seite erhalten Sie eine kontextabhängige Kurzhilfe und können weitergehende Informationen abrufen.</p>	</text></chapter>
