=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/resources/documentation.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.xml-sicherheit.de" targetNamespace="http://www.xml-sicherheit.de" xml:lang="en">	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>	<xs:annotation>		<xs:documentation xml:lang="en">			XML-Security Plug-in documentation schema. Used for online help and tutorials.		</xs:documentation>	</xs:annotation>	<xs:element name="title" type="xs:string"/>	<xs:element name="strong" type="xs:string"/>	<xs:element name="keyword" type="xs:string"/>	<xs:element name="definition" type="xs:string"/>	<xs:element name="description" type="xs:string"/>	<xs:element name="headline">		<xs:complexType>			<xs:simpleContent>				<xs:extension base="xs:string">					<xs:attribute name="id" type="xs:ID" use="required"/>				</xs:extension>			</xs:simpleContent>		</xs:complexType>	</xs:element>	<xs:element name="data">		<xs:complexType mixed="true">			<xs:sequence>				<xs:element ref="strong" minOccurs="0" maxOccurs="unbounded"/>				<xs:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="acronyms">		<xs:complexType>			<xs:sequence>				<xs:element ref="acronym" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="acronym">		<xs:complexType>			<xs:sequence>				<xs:element ref="definition"/>				<xs:element ref="description"/>			</xs:sequence>			<xs:attribute name="abbreviation" type="xs:ID" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="chapter">		<xs:complexType>			<xs:sequence>				<xs:element ref="title" minOccurs="0"/>				<xs:element ref="text"/>			</xs:sequence>			<xs:attribute name="category" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="general"/>						<xs:enumeration value="basics"/>						<xs:enumeration value="plugin"/>						<xs:enumeration value="resources"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute ref="xml:lang" use="required"/>			<xs:attribute ref="xml:id" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="text">		<xs:complexType>			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="p"/>				<xs:element ref="list"/>				<xs:element ref="code"/>				<xs:element ref="table"/>				<xs:element ref="headline"/>				<xs:element ref="link"/>				<xs:element ref="image"/>				<xs:element ref="resources" minOccurs="0"/>				<xs:element ref="acronyms" minOccurs="0"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="p">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="strong"/>				<xs:element ref="keyword"/>				<xs:element ref="link"/>				<xs:element ref="eclipse"/>			</xs:choice>			<xs:attribute name="id" type="xs:ID" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="list">		<xs:complexType>			<xs:choice maxOccurs="unbounded">				<xs:element ref="point"/>				<xs:element ref="list"/>			</xs:choice>			<xs:attribute name="type" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="ordered"/>						<xs:enumeration value="unordered"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="point">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="strong"/>				<xs:element ref="keyword"/>				<xs:element ref="link"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="link">		<xs:complexType mixed="true">			<xs:sequence>				<xs:element ref="image" minOccurs="0"/>			</xs:sequence>			<xs:attribute name="id" type="xs:anyURI" use="required"/>		</xs:complexType>	</xs:element>	<xs:element name="image">		<xs:complexType>			<xs:attribute name="id" type="xs:anyURI" use="required"/>			<xs:attribute name="title" type="xs:string" use="required"/>			<xs:attribute name="width" use="required">				<xs:simpleType>					<xs:restriction base="xs:positiveInteger">						<xs:minInclusive value="1"/>						<xs:maxInclusive value="800"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute name="height" use="required">				<xs:simpleType>					<xs:restriction base="xs:positiveInteger">						<xs:minInclusive value="1"/>						<xs:maxInclusive value="800"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="table">		<xs:complexType>			<xs:sequence>				<xs:element ref="head"/>				<xs:element ref="row" maxOccurs="unbounded"/>			</xs:sequence>			<xs:attribute name="width" type="xs:positiveInteger" use="optional"/>			<xs:attribute name="border" type="xs:positiveInteger" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="head">		<xs:complexType>			<xs:sequence>				<xs:element ref="data" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="row">		<xs:complexType>			<xs:sequence>				<xs:element ref="data" maxOccurs="unbounded"/>			</xs:sequence>			<xs:attribute name="valign" type="xs:string" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="resources">		<xs:complexType>			<xs:sequence>				<xs:element ref="title"/>				<xs:element ref="link" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="code">		<xs:complexType mixed="true">			<xs:choice minOccurs="0" maxOccurs="unbounded">				<xs:element ref="link"/>			</xs:choice>		</xs:complexType>	</xs:element></xs:schema>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../resources/stylesheet.xsl"?>
<chapter category="general" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="intro" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../resources/documentation.xsd">
	<text>
		<p>Dieses Tutorial ist Bestandteil des <strong>XML-Security Plug-In</strong>, dem Open Source eLearning Plug-in für XML-Sicherheit mit Eclipse ab Version 3.0. Mit dem XML-Security Plug-In können Sie beliebige XML-Dokumente sichern und <keyword>XML Canonicalization</keyword>, <keyword>XML Digitale Signaturen</keyword> sowie <keyword>XML Verschlüsselung</keyword> in beliebigen XML-Dokumenten ausprobieren und anwenden. Verschiedene Cheat Sheets erleichtern Einsteigern die ersten Schritte mit dem Plug-in und der XML-Sicherheit. Die umfangreiche Online-Hilfe des Plug-ins enthält ausführliche Informationen zu den W3C Empfehlungen und Hintergründe zu den digitalen Signaturen und der Verschlüsselung mit der Extensible Markup Language sowie Erläuterungen zur Verwendung des XML-Security Plug-Ins.</p>
		<p>Im Vordergrund des XML-Security Plug-Ins stehen die praktische Anwendung und das Experimentieren mit den vielfältigen Möglichkeiten der XML-Sicherheit: beliebige XML-Dokumente können kanonisiert, digital signiert, verifiziert sowie ver- und entschlüsselt werden. Die theoretischen Kenntnisse und Hintergründe zu den umfangreichen W3C Empfehlungen stehen in der ausführlichen Online-Hilfe und diesen Tutorials verständlich zum Nachlesen bereit.</p>
		<p>Für das XML-Security Plug-In sind Kenntnisse in <keyword>XML</keyword> erforderlich, <keyword>XPath Expressions</keyword> und <keyword>Namespaces</keyword> sind hilfreich aber nicht zwingend notwendig. Empfehlenswert sind außerdem Kenntnisse in <keyword>XML Schema (XSD)</keyword>, <keyword>Document Type Definition (DTD)</keyword> und <keyword>XSL Transformations (XSLT)</keyword>. Kenntnisse in der <keyword>Kryptografie</keyword> (Digitale Signaturen, Verschlüsselung, Hashfunktionen) sind hilfreich aber nicht unbedingt erforderlich. Für das XML-Security Plug-In sollten dafür grundlegende <keyword>Eclipse</keyword> Kenntnisse vorhanden sein.</p>
		<p>Die Homepage zum <strong>XML-Security Plug-In</strong> und zur <strong>XML-Sicherheit</strong> für Support, Tipps, Update Site und vielem mehr ist verfügbar unter <link id="http://www.xml-sicherheit.de/">http://www.xml-sicherheit.de</link>. Der Source Code des Plug-ins findet sich auf der SourceForge Projektseite unter <link id="http://sourceforge.net/projects/xml-security">http://sourceforge.net/projects/xml-security</link>.</p>
		<p>Das <strong>XML-Security Plug-In</strong> steht unter der <keyword>Eclipse Public License Version 1.0</keyword>, einsehbar unter <link id="http://www.eclipse.org/legal/epl-v10.html">http://www.eclipse.org/legal/epl-v10.html</link>. Die für das XML-Security Plug-in notwendige Apache XML Security API (<keyword>Santuario</keyword>) im Plug-in <strong>org.apache.xml.security</strong> sowie Apache Xalan im Plug-in <strong>org.apache.xalan</strong> stehen unter der <keyword>Apache Software License Version 2.0</keyword>. Diese ist einsehbar unter <link id="http://www.apache.org/licenses/LICENSE-2.0.html">http://www.apache.org/licenses/LICENSE-2.0.html</link>.</p>
		<p>Seit Oktober 2008 ist das XML-Security Plug-In ein offizielles Eclipse Plug-in und wird nicht mehr eigenständig weiterentwickelt. Unter dem Namen <strong>XML Security Tools</strong> sind neue Versionen des Plug-ins nun im Incubator der <link id="http://www.eclipse.org/webtools/incubator/">Eclipse Web Tools Platform (WTP)</link> zu finden.</p>
		<p>Fehler im Tutorial? Unverständliche oder unvollständige Erklärung? Mehr Informationen gewünscht? Den Entwickler und Autor Dominik Schadow erreichen Sie per Email über <link id="mailto:info@xml-sicherheit.de">info@xml-sicherheit.de</link> oder über die zahlreichen Kontaktmöglichkeiten auf der Homepage.</p>
	</text>
</chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/overview.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../resources/stylesheet.xsl"?><chapter category="general" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="overview" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../resources/documentation.xsd">	<title>Übersicht</title>	<text>		<p>Der XML Security Guide besteht aus den beiden Teilen <link id="basics/xml-security.html">XML-Security Basics</link> und <link id="plugin/plugin.html">XML-Security Plug-In</link>. Im theoretischen ersten Teil finden Sie ausführliche und verständliche Informationen über die Empfehlungen des World Wide Web Consortiums (W3C) zu den digitalen Signaturen (<keyword>XML Digital Signatures</keyword>) und der Verschlüsselung (<keyword>XML Encryption</keyword>) mit XML, zum Basic Security Profile (BSP) und anderen verwandten Themen wie der Kanonisierung (<keyword>XML Canonicalization</keyword>). Kenntnisse in diesen Themen sind Vorraussetzung um effektiv mit dem XML-Security Plug-In arbeiten zu können. Im praktischen zweiten Teil des Guides erhalten Sie umfassende und verständliche Anleitungen zur Verwendung des XML-Security Plug-Ins.</p>		<p>Weiterführende Informationen und Grundlagen zu XML und der Kryptografie finden Sie unter <link id="literature.html">Literatur</link> und <link id="resources.html">Ressourcen</link>. Im <link id="glossary.html">Glossar</link> finden Sie wichtige Abkürzungen aus dem Bereich der XML-Sicherheit und eine kurze Beschreibung.</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/glossary.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../resources/stylesheet.xsl"?><chapter category="general" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="glossary" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../resources/documentation.xsd">	<title>Glossar</title>	<text>		<acronyms>			<acronym abbreviation="AES">				<definition>Advanced Encryption Standard</definition>				<description>Blockchiffre mit variabler Schlüssellänge von 128, 192 oder 256 Bit. 2001 vom NIST zum DES Nachfolger bestimmt</description>			</acronym>			<acronym abbreviation="ASN.1">				<definition>Abstract Syntax Notation One</definition>				<description>Notationsart für die Beschreibung von abstrakten Datentypen und Werten</description>			</acronym>			<acronym abbreviation="BSP">				<definition>Basic Security Profile</definition>				<description>Herstellerunabhängige Empfehlung mit dem Ziel maximaler Interoperabilität und einfachem Datenaustausch</description>			</acronym>			<acronym abbreviation="CBC">				<definition>Cipher Block Chaining</definition>				<description>Symmetrische Blockchiffre - der folgende Block wird mit dem vorherigen verknüpft, erster Block beliebig</description>			</acronym>			<acronym abbreviation="CEK">				<definition>Content Encryption Key</definition>				<description>Verschlüsselt die Nutzdaten einer Kommunikation - aus Geschwindigkeitsgründen meist symmetrische Schlüssel</description>			</acronym>			<acronym abbreviation="CFB">				<definition>Cipher Feedback</definition>				<description>Symmetrische Blockchiffre - Pseudozufallsgenerator zur Erzeugung einer Schlüsselfolge</description>			</acronym>			<acronym abbreviation="CSP">				<definition>Cryptographic Service Provider</definition>				<description>Stellt kryptografische Funktionalität bereit</description>			</acronym>			<acronym abbreviation="DES">				<definition>Data Encryption Standard</definition>				<description>Mittlerweile als unsicher (zu geringe Schlüssellänge) betrachteter symmetrischer Algorithmus</description>			</acronym>			<acronym abbreviation="DES-EDE">				<definition>Data Encryption Standard-Encryption Decryption Encryption</definition>				<description>Verbesserter DES Algorithmus durch längeren Schlüssel (auch Triple DES genannt)</description>			</acronym>			<acronym abbreviation="DH">				<definition>Diffie-Hellman</definition>				<description>1976 als erstes Public-Key-Verfahren vorgestellt, basiert auf dem ElGamal Algorithmus</description>			</acronym>			<acronym abbreviation="DSA">				<definition>Digital Signature Algorithm</definition>				<description>Reiner Signaturalgorithmus vom NIST und der NSA 1991 entwickelt</description>			</acronym>			<acronym abbreviation="DSS">				<definition>Digital Signature Standard</definition>				<description>Spezifiziert den Digital Signature Algorithm (DSA)</description>			</acronym>			<acronym abbreviation="DTD">				<definition>Document Type Definition</definition>				<description>Formale Sprache (nicht in XML-Syntax) zur Festlegung der Struktur eines XML-Dokuments</description>			</acronym>			<acronym abbreviation="ECB">				<definition>Electronic Code Book</definition>				<description>Symmetrische Blockchiffre - jeder Block Text wird separat verschlüsselt, gleicher Text mit gleichem Schlüssel gibt gleiche Chiffre</description>			</acronym>			<acronym abbreviation="IDEA">				<definition>International Data Encryption Algorithm</definition>				<description>1990 veröffentlichter, patentierter, symmetrischer Blockverschlüsselungsalgorithmus</description>			</acronym>			<acronym abbreviation="IETF">				<definition>Internet Engineering Task Force</definition>				<description>Internationale Vereinigung zur Erarbeitung von Standardisierungsvorschlägen für das Internet</description>			</acronym>			<acronym abbreviation="KEK">				<definition>Key Encryption Key</definition>				<description>Verschlüsselt (symmetrisch und asymmetrisch) nur den Schlüssel (CEK) und keine Nutzdaten</description>			</acronym>			<acronym abbreviation="MD2-MD5">				<definition>Message Digest</definition>				<description>Von Ron Rivest entwickelte Hashfunktionen - aktuell MD5, sehr weit verbreitet (Schwächen bekannt)</description>			</acronym>			<acronym abbreviation="MIME">				<definition>Multipurpose Internet Mail Extensions</definition>				<description>Kodierungsstandard zur Festlegung der Struktur und des Aufbaus von Emails und anderen Internetnachrichten</description>			</acronym>			<acronym abbreviation="NIST">				<definition>National Institute of Standards and Technology</definition>				<description>US Behörde für technologische Standardisierungsprozesse</description>			</acronym>			<acronym abbreviation="OASIS">				<definition>Organisation for the Advancement of Structured Information Standards</definition>				<description>Internationales Standardisierungsgremium zur Weiterentwicklung von E-Business- und Web Service Standards</description>			</acronym>			<acronym abbreviation="OCSP">				<definition>Online Certificate Status Protocol</definition>				<description>Internetprotokoll mit dem Clients den Status von X.509 Zertifikaten abfragen können</description>			</acronym>			<acronym abbreviation="OFB">				<definition>Output Feedback</definition>				<description>Symmetrische Blockchiffre - Pseudozufallsgenerator zur Erzeugung einer Schlüsselfolge</description>			</acronym>			<acronym abbreviation="PBE">				<definition>Password-based Encryption</definition>				<description>Der Schlüssel wird aus einem Kennwort generiert</description>			</acronym>			<acronym abbreviation="PCBC">				<definition>Propagating Cipher Block Chaining</definition>				<description>Symmetrische Blockchiffre ähnlich CBC - der vorige Klartextblock und der vorige Chiffretextblock werden mit dem aktuellen Klartextblock XOR-verknüpft</description>			</acronym>			<acronym abbreviation="PKI">				<definition>Public Key Infrastructure</definition>				<description>Infrastruktur zur Verteilung öffentlicher Schlüssel</description>			</acronym>			<acronym abbreviation="RC2-RC6">				<definition>Rons Cipher</definition>				<description>Verschlüsselungsalgorithmus mit variabler Schlüssellänge, erste Version 1989 von Ron Rivest - aktuell RC6, Vorversionen als unsicher betrachtet (bzw. gebrochen)</description>			</acronym>			<acronym abbreviation="RSA">				<definition>Rivest, Shamir, Adleman</definition>				<description>1977 von Rivest, Shamir und Adleman vorgestellter Algorithmus - bekannt vor allem durch die Verwendung in PGP zur asymmetrischen Verschlüsselung</description>			</acronym>			<acronym abbreviation="SAML">				<definition>Security Assertion Markup Language</definition>				<description>XML-basierte Spezifikation zur Definition von sicherheitsrelevanten Informationen zur Authentifizierung, Autorisierung und Anwender-Attributen sowie Berechtigungs-Schemata</description>			</acronym>			<acronym abbreviation="SHA">				<definition>Secure Hash Algorithm</definition>				<description>Speziell zum Signieren entwickelter Hashalgorithmus mit einem 160 Bit langen Hashwert für DSS</description>			</acronym>			<acronym abbreviation="SOAP">				<definition>ursprünglich: Simple Object Access Protocol</definition>				<description>Protokoll zum Übermittlung von XML-Nachrichten, SOAP ist seit Version 1.2 kein Akronym mehr</description>			</acronym>			<acronym abbreviation="URI">				<definition>Uniform Resource Identifier</definition>				<description>Zeichenfolge zur Identifizierung einer abstrakten oder physikalischen Ressource</description>			</acronym>			<acronym abbreviation="W3C">				<definition>World Wide Web Consortium</definition>				<description>Gremium zur Standardisierung von Techniken rund um das World Wide Web</description>			</acronym>			<acronym abbreviation="WSS">				<definition>Web Service Security (auch WS-Security)</definition>				<description>Umfangreiche Empfehlungen rund um die Sicherheit von Web Services</description>			</acronym>			<acronym abbreviation="XAdES">				<definition>XML Advanced Electronic Signatures</definition>				<description>Ergänzung von Cisco mit deren Hilfe die Nicht-Abstreitbarkeit für XML-Signaturen umgesetzt werden kann</description>			</acronym>			<acronym abbreviation="XKMS">				<definition>XML Key Management Specification</definition>				<description>PKI Funktionen basierend auf XML als Beschreibungssprache für den Nachrichtenaustausch der Teilnehmer</description>			</acronym>			<acronym abbreviation="X-KISS">				<definition>XML Key Information Service Specification</definition>				<description>Spezifikation zur Suche und Validierung von öffentlichen Schlüsseln</description>			</acronym>			<acronym abbreviation="X-KRSS">				<definition>XML Key Registration Service Specification</definition>				<description>Spezifikation zur Erstellung, Registrierung und dem Widerruf von Schlüsseln</description>			</acronym>			<acronym abbreviation="XML">				<definition>Extensible Markup Language</definition>				<description>Erweiterbare Metasprache des W3C zur Dokumentenauszeichnung in maschinen- und menschenlesbarer Form</description>			</acronym>		</acronyms>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/resources/encryption_resources.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href../../resources/stylesheet.xsl"?><chapter category="resources" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="encryption_resources" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<text>		<resources>			<title>Online Resources</title>			<link id="http://www.w3.org/TR/xml-encryption-req">XML Encryption Requirements</link>			<link id="http://www.w3.org/TR/xmlenc-core/xenc-schema.xsd">XML Encryption Schema</link>			<link id="http://www.w3.org/TR/xmlenc-core">XML Encryption Syntax and Processing 1.0</link>            <link id="http://www.w3.org/TR/xmlenc-core1">XML Encryption Syntax and Processing 1.1</link>			<link id="http://www.w3.org/Encryption/2001">XML Encryption Working Group</link>		</resources>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/plugin/sign_page_create_key.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="plugin" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="sign_page_create_certificate" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Create a new Key</title>	<text>		<p>Auf dieser zweiten Seite des <keyword>Digital Signature Wizard</keyword> können Sie einen neuen Schlüssel in einem vorhandenen Java Keystore generieren. Nach Angabe aller erforderlichen Daten wird das Zertifikat unter dem von Ihnen angegebenen <keyword>Alias</keyword> im ausgewählten Keystore gespeichert und zur Generierung dieser digitalen Signatur verwendet.</p>		<image id="../images/dsig-2b.png" title="Create a new Certificate" width="275" height="392"/>		<p>Zunächst müssen Sie die Daten für den <keyword>Distinguished Name</keyword> angeben. Dazu gehören <keyword>Common Name</keyword>, <keyword>Organizational Unit</keyword>, <keyword>Organization</keyword>, <keyword>Location</keyword>, <keyword>State</keyword> und <keyword>Country</keyword>. Lediglich der <keyword>Common Name</keyword> ist ein Pflichtfeld, die anderen fünf sind optional. Während der Eingabe der Daten zeigt das Vorschaufeld eine Übersicht Ihrer getätigten Eingaben an.</p>		<p>Anschließend sind einige Angaben zum Schlüssel (<keyword>Key</keyword>) erforderlich. Der <keyword>Alias</keyword> ist ein Pflichtfeld und muss zwischen 4 und 20 Zeichen lang sein. Das <keyword>Password</keyword> für das Zertifikat ist ebenfalls ein Pflichtfeld und muss mindestens 6, maximal jedoch 20 Zeichen lang sein. Mit dem <strong>Punkt</strong> Button rechts neben den Eingabefeld können Sie sich den Klartext anzeigen lassen und Ihre Eingabe kontrollieren. Aus der <keyword>Type</keyword> Auswahlbox können Sie jetzt noch den Typ des Zertifikats auswählen. Möglich sind <keyword>Digital Signature Algorithm (DSA)</keyword>, <keyword>Elliptic Curve DSA (ECDSA)</keyword> und <keyword>Rivest, Shamir, Adleman (RSA)</keyword>.</p>		<p>Jetzt müssen Sie noch den Java Keystore (mit der Dateiendung <keyword>.jks</keyword>) angeben, den Sie um das neue Zertifikat erweitern wollen. Über den Button <strong>Open...</strong> öffnen Sie das Standarddialogfeld zur Auswahl einer solchen Datei. Damit das Zertifikat darin gespeichert werden kann ist noch die Eingabe des Keystore Passworts im <keyword>Password</keyword> Feld erforderlich. Mit dem <strong>Punkt</strong> Button rechts neben den Eingabefeld können Sie sich den Klartext anzeigen lassen und Ihre Eingabe kontrollieren.</p>		<p>Nach der korrekten Angabe aller erforderlichen Daten können Sie das Zertifikat über den Button <strong>Create Certificate</strong> generieren und im angegebenen Keystore speichern lassen.</p>		<p>Das generierte Zertifikat können Sie in Zukunft über die Seite <link id="sign_page_open_certificate.html">Open an existing Certificate</link> direkt verwenden. Dazu benötigen Sie neben dem Dateinamen die unter <keyword>Certificate Alias</keyword>, <keyword>Certificate Password</keyword> und <keyword>Keystore Password</keyword> angegebenen Daten.</p>		<p>Nach der erfolgreichen Generierung des neuen Zertifikats können Sie mit dem <strong>Next</strong> Button auf die nächste Seite des Digital Signature Wizards wechseln: <link id="sign_page_algorithms.html">Algorithms and Signature Properties</link>.</p>	</text></chapter>

=== chandu1988/XMLExamples/de.xmlsicherheit.tutorials/xml/plugin/canonicalize.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../resources/stylesheet.xsl"?><chapter category="plugin" xmlns="http://www.xml-sicherheit.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:id="canonicalize" xml:lang="de" xsi:schemaLocation="http://www.xml-sicherheit.de ../../resources/documentation.xsd">	<title>Canonicalization</title>	<text>		<p>Mit den Menüeinträgen <strong>Canonicalization without comments</strong> und <strong>Canonicalization with comments</strong> aus dem Kontextmenü können Sie das gewählte XML-Dokument mit der <keyword>Exclusive XML Canonicalization</keyword> oder <keyword>Inclusive XML Canonicalization</keyword> kanonisieren. Ob die <keyword>exclusive</keyword> oder die <keyword>inclusive</keyword> Variante verwendet wird und ob das XML-Dokument direkt aktualisiert wird oder ein weiteres Editorfenster mit der kanonisierten Version erstellt wird hängt von den Einstellungen in den <link id="prefs.html">Preferences</link> ab. Beim Aufruf über eine View wie den Navigator und der Zieldokument Einstellung <keyword>New Document</keyword> wird das kanonisierte XML-Dokument als <keyword>[Dateiname]_canon.xml</keyword> im aktuellen Projekt gespeichert.</p>		<p>Wenn Sie <strong>Canonicalization without comments</strong> auswählen werden die Kommentare im XML-Dokument entfernt und durch Leerzeilen ersetzt, bei <strong>Canonicalization with comments</strong> bleiben die Kommentare erhalten. In jedem Fall wird der Befehl sofort ausgeführt (ohne Assistent) und das XML-Dokument entweder im Editor aktualisiert oder im Dateisystem gespeichert.</p>		<p>Die Kanonisierung ist an sich ein sehr einfacher Vorgang. Mit der Möglichkeit diese separat auszuführen sollen Ihnen vor allem die Vorgänge bei der Signierung verdeutlicht werden, was sich hinter dem Stichwort <keyword>Kanonisierung</keyword> verbirgt und welche Veränderungen dabei in einem XML-Dokument durchgeführt werden. Die Kanonisierung ist einer der wichtigsten Vorgänge die unter anderem bei der Signierung vor den Blicken des Benutzers verborgen ablaufen.</p>	</text></chapter>
